<?php
/**
 * Created by PhpStorm.
 * User: Smart
 * Date: 16.12.2016 г.
 * Time: 17:30 ч.
 */

namespace RpgBundle\Repository;

/**
 * BuildingCostResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingCostResourceRepository extends \Doctrine\ORM\EntityRepository
{
}