<?php
/**
 * Created by PhpStorm.
 * User: Smart
 * Date: 16.12.2016 г.
 * Time: 17:22 ч.
 */

namespace RpgBundle\Repository;
/**
 *  BuildingCostTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BuildingCostTimeRepository extends \Doctrine\ORM\EntityRepository
{

}