<?php
/**
 * Created by PhpStorm.
 * User: Smart
 * Date: 16.12.2016 г.
 * Time: 15:59 ч.
 */


namespace RpgBundle\Repository;

/**
 * PlanetBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
